name: reploy

on:
  push
  # workfolw_dispatch:
jobs:
#   job1:
#     runs-on: ubuntu-latest
#     setps:
#       - run: pwl
#       - run: ls
  job2:
    runs-on: windows-latest
    steps:
      - run: node --version
